### ISSUE TITLE
FirebaseError: Installations: Missing App configuration values. (installations/missing-app-config-values).

### ISSUE THREAD

**Issue by uokivan** [kenng/firebase-push-notification-demo#10]
Hi
on my webpage,
after show me : "Notification permission granted."

it will shows :
; FirebaseError: Installations: Missing App configuration values. (installations/missing-app-config-values).

How to fix it ?
Thanks a lot

**Comment by kenng** [comment]
Hi @uokivan ,
According to https://github.com/firebase/firebase-js-sdk/issues/2287#issuecomment-553860831
```
Previously, having {messagingSenderId: 'idgoeshere'} was sufficient config for firebase messaging:
932d7be#diff-0cdfe633d7740a89cc1b6a290f988ff9L63

Now, all of these (apiKey, projectId, appId) are needed too: 932d7be#diff-f169866494446eb62e44e7b87d1cdad2R22-R35
```

We have updated the blog, https://www.itwonders-web.com/blog/push-notification-using-firebase-demo-tutorial, if you have tested and it works, you can create a pull request for the update. Thanks.
