### ISSUE TITLE
Create Installation Request Failed

### ISSUE THREAD

**Issue by bhaskartalla** [kenng/firebase-push-notification-demo#11]
Does any know how to solve this issue?
Unable to get permission to notify. FirebaseError: Installations: Create Installation request failed with error "403 PERMISSION_DENIED: Requests to this API firebaseinstallations.googleapis.com method google.firebase.installations.v1.FirebaseInstallationsService.CreateInstallation are blocked." (installations/request-failed).

**Comment by kenng** [comment]
@bhaskartalla Not very sure, perhaps you can check with the updated source code again and see, as it is working fine here.
