### ISSUE TITLE
manifest.json

### ISSUE THREAD

**Issue by aghasemi** [kenng/firebase-push-notification-demo#12]
Hi and thanks for the tutorial!

For me it only showed the sent notifications after adding this manifest.json file to the project root (See [here](https://github.com/firebase/quickstart-js/blob/1c8f12a31687698d90af50c105b0db71a25f837a/messaging/manifest.json)):

``` json
{
  "//_comment1": "Some browsers will use this to enable push notifications.",
  "//_comment2": "It is the same for all projects, this is not your project's sender ID",
  "gcm_sender_id": "103953800507"
}

```
Thanks
Best

**Comment by kenng** [comment]
@aghasemi thanks for sharing this info, it seems that this is needed for some browsers, just quick check which browser and the version that you are using?

https://developers.google.com/web/updates/2016/07/web-push-interop-wins#reality_of_these_changes
```
Reality of these changes
With VAPID you no longer need to sign up for an account with GCM to use push in Chrome and you can use the same code path for subscribing a user and sending a message to a user in both Chrome and Firefox. Both are following the standards.

What you need to bear in mind is that in Chrome 51 and before, Opera for Android and Samsung browser you'll still need to define the gcm_sender_id in your web app manifest and you'll need to add the Authorization header to the FCM endpoint that will be returned.

VAPID provides an off ramp from these proprietary requirements. If you implement VAPID it'll work in all browsers that support web push. As more browsers support VAPID you can decide when to drop the gcm_sender_id from your manifest.
```

**Comment by aghasemi** [comment]
Chrome 87.

I may be lost here, but your example doesn't use VAPID. Does it?

**Comment by miloskroulik** [comment]
I was wondering about VAPID as well. Official quickstart clearly mentions it ssould be used: https://github.com/firebase/quickstart-js/tree/master/messaging

**Comment by kenng** [comment]
> I was wondering about VAPID as well. Official quickstart clearly mentions it ssould be used: https://github.com/firebase/quickstart-js/tree/master/messaging

The vapidKey config is optional but in some services it is needed. Too bad I have not able to test it out, I guess providing vapid key cause no harm and will definitely fix issue like this. Thanks for raising this.

https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging
>Optional vapidKey?: string
The public server key provided to push services. It is used to authenticate the push subscribers to receive push messages only from sending servers that hold the corresponding private key. If it is not provided, a default VAPID key is used. Note that some push services (Chrome Push Service) require a non-default VAPID key. Therefore, it is recommended to generate and import a VAPID key for your project with Configure Web Credentials with FCM. See The Web Push Protocol for details on web push services.}

**Comment by kenng** [comment]
> Chrome 87.
> 
> I may be lost here, but your example doesn't use VAPID. Does it?

Ya, the example was working on my side without `gcm_sender_id`, so i guess the chrome version might be the one. See the Documentation

https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications
> Note: The gcm_sender_id is required for Chrome prior to version 52, Opera Android, and Samsung Internet.

**Comment by kenng** [comment]
fixed with #caedea8

**Comment by kenng** [comment]
caedea8

**Comment by kenng** [comment]
closed with https://github.com/kenng/firebase-push-notification-demo/commit/caedea8a8bedd77431e8adc62c47c870a706315c
