### ISSUE TITLE
Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script. 

### ISSUE THREAD

**Issue by trungducng** [kenng/firebase-push-notification-demo#2]
THis repo seems to be similar to the tutorial from Firebase for web push notification. I mean it look great and is supposed to work flawlessly. However, I always face with the problem involve in service worker, in ur tutorial and others dont mention about that. 

Any recommendations to fix this issue?

**Comment by subhashD** [comment]
Why this issue has been closed. There is no solution given for this
