### ISSUE TITLE
Can I put a notification bell icon on website

### ISSUE THREAD

**Issue by bsde1234** [kenng/firebase-push-notification-demo#7]
Can I put a notification bell icon in the website so that on clicking it user can subscribe to website? How to do it?

Also I think we need to collect tokens to somewhere right? Do I need to use database for this?

**Comment by kenng** [comment]
yes, you can add the button for subscribe/unsubcribe then handling it separately. 

Yap, token you will have to save it to database, be it firestore or your own SQL. 

closing since it's not issue.
