### ISSUE TITLE
Foreground messages will not show notifications

### ISSUE THREAD

**Issue by TylerByte666** [kenng/firebase-push-notification-demo#8]
Hi, so this source works for back grounded browser tabs or even closed browser tabs.  But sending that same json body never fires off the handler in index.html:

`messaging.onMessage((payload) => {
                console.log('Message received. ', payload);            
 });`

 Any ideas?

**Comment by kenng** [comment]
can you try and let me know if it works
```
messaging.onMessage(payload => {
  const {title, ...options} = payload.notification;
  navigator.serviceWorker.ready.then(registration => {
    registration.showNotification(title, options);
  });
});
```

[create-firebase-notification-with-page-in-foreground-focus](https://stackoverflow.com/questions/40411059/create-firebase-notification-with-page-in-foreground-focus)

**Comment by TylerByte666** [comment]
> 
> 
> can you try and let me know if it works
> 
> ```
> messaging.onMessage(payload => {
>   const {title, ...options} = payload.notification;
>   navigator.serviceWorker.ready.then(registration => {
>     registration.showNotification(title, options);
>   });
> });
> ```
> 
> [create-firebase-notification-with-page-in-foreground-focus](https://stackoverflow.com/questions/40411059/create-firebase-notification-with-page-in-foreground-focus)

Thank you I will do 😄

**Comment by TylerByte666** [comment]
Hi, it works. But Before I was not even getting the console log saying: 

> Message received.  payload data.

So it turn out it was my sw, it was pointing to another sender-id, so my other app was getting all the notifications.

Your script works, it does show push notifications in foreground, really cool ❤️ Thank you for this.
I gave it an upgrade to 7.2.1 as well 👍

**Comment by hoangtuan151** [comment]
> can you try and let me know if it works
> 
> ```
> messaging.onMessage(payload => {
>   const {title, ...options} = payload.notification;
>   navigator.serviceWorker.ready.then(registration => {
>     registration.showNotification(title, options);
>   });
> });
> ```
> 
> [create-firebase-notification-with-page-in-foreground-focus](https://stackoverflow.com/questions/40411059/create-firebase-notification-with-page-in-foreground-focus)

Hi there,

I've make some test on web app, this code will show notification in notification tray when web app is on foreground, but I'm getting 2 problems:
- Nothing happened when clicking notification (the notification was not removed from tray)
- Chrome show extra notification on tray: "This site has been updated in the background"

Suppose that, my push json message is:

```
{
"message":{
    "webpush": {
        "notification": {
            "title": "push title",
            "body": "push body"
        },
        "fcm_options": {
            "link": "https://mypage.com"
        }
    },
  "token": "cw..."
  }
}
```

How could we overcome these issues?

Thank in advanced!
